name = "SIMDiff"
uuid = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
authors = ["Sungho Shin <sshin@anl.gov>"]
version = "0.1.0"

[deps]
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[compat]
julia = "1.9"
KernelAbstractions = "0.9"

[weakdeps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
SIMDiffSpecialFunctions = "SpecialFunctions"
SIMDiffKernelAbstractions = "KernelAbstractions"
SIMDiffCUDA = "CUDA"
SIMDiffOneAPI = "oneAPI"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"

[targets]
test = ["Test", "NLPModelsIpopt", "ADNLPModels"]
